name: Django CI run test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: ['3.12', '3.13']

    steps:
    - uses: actions/checkout@v6
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v6
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r test-requirements.txt
    - name: Run Ruff
      run: ruff check --output-format=github .
    - name: Run Tests
      run: pytest friendly_captcha/tests.py

  Coverage:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v6
    - name: Set up Python 3.13
      uses: actions/setup-python@v6
      with:
        python-version: '3.13'
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r test-requirements.txt
    - name: Create coverage report
      run: pytest --cov --cov-report=xml friendly_captcha/tests.py
    - name: Upload to codecov.io
      uses: codecov/codecov-action@v7
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

    - name: Archive code coverage results
      uses: actions/upload-artifact@v7
      with:
        name: code-coverage-report
        path: coverage.xml
